name: Publish GitHub Release Notes to WordPress

on:
  release:
    types: [published]

jobs:
  publish_release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Publish Release Notes to WordPress
        env:
          WP_API_URL: ${{ secrets.WP_API_URL }}      
          WP_USERNAME: ${{ secrets.WP_USERNAME }}          
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}  
          RELEASE_TITLE: ${{ github.event.release.name }}
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          curl -X POST "$WP_API_URL" \
            -H "Content-Type: application/json" \
            -u "$WP_USERNAME:$WP_APP_PASSWORD" \
            -data-binary @- << EOF
                {
                  "title": "'"$RELEASE_TITLE"'",
                  "content": "'"$RELEASE_BODY"'",
                  "status": "publish"
                }
            EOF
       
