name: Publish GitHub Release Notes to WordPress

on:
  release:
    types: [published]

jobs:
  publish_release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Publish Release Notes to WordPress
        env:
          WP_API_URL: ${{ secrets.WP_API_URL }}      
          WP_USERNAME: ${{ secrets.WP_USERNAME }}          
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}  
        run: |
          echo $WP_API_URL
          echo $WP_USERNAME
          echo $WP_APP_PASSWORD
          curl -X POST "$WP_API_URL" \
            -H "Content-Type: application/json" \
            -u "$WP_USERNAME:$WP_APP_PASSWORD" \
            -d '{
                  "title": "Test Title",
                  "content": "Test Body",
                  "status": "publish"
                }'
       
